import "./globals.css";
import localfont from "@next/font/local";

const din = localfont({
  src: [
    {
      path: "../public/fonts/DIN.ttf",
      weight: "400",
    },
    {
      path: "../public/fonts/DIN-Medium.ttf",
      weight: "500",
    },
    {
      path: "../public/fonts/Din-Bold.ttf",
      weight: "700",
    },
    {
      path: "../public/fonts/Din-Black.ttf",
      weight: "900",
    },
  ],
  variable: "--font-din",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${din.variable} font-sans`}>
      <body className="overflow-y-hidden">{children}</body>
    </html>
  );
}
